cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/sdn/ybd/LHCC/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/sdn/ybd/LHCC/simulation/.waf-1.7.11-edc6ccb516c5e3f9b892efc9f53a610f/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139845084881168: cxx test.cpp -> test.cpp.1.o}\n[\'g++-5\', \'-O0\', \'-ggdb\', \'-g3\', \'-std=gnu++11\', \'-DNS3_ASSERT_ENABLE\', \'-DNS3_LOG_ENABLE\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
